scss:
  enabled: false

stylelint:
  enabled: true

ruby:
  enabled: false

jshint:
  enabled: false

eslint:
  enabled: true
  config_file: './app/javascript/.eslintrc.js'
  ignore_file: .eslintignore

fail_on_violations: true
